server:
  port: 80

spring:
  application:
    name: cloud-order-service
  zipkin:
      base-url: http://localhost:9411 #zipkin监控界面地址
      sleuth:
        sampler:
         #采样率值介于0到1之间,0不采,0.5采一半,1则表示全部采集
         probability: 1


eureka:
  client:
    #表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓,集群必须设置true才能配合ribbon使用负载均衡
    fetchRegistry: true
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
        #      defaultZone: http://localhost:7001/eureka  #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
