server:
  port: 7002

eureka:
  instance:
    #eureka服务端的实例名字
    hostname: eureka7002.com
  client:
    #是否要将自身的实例信息注册到 Eureka Server
    register-with-eureka: false
    #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址 localhost：7001
    #这里的eureka7001.com，eureka7002.com是在hosts文件做了映射  =127.0.0.1
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #集群版
      #defaultZone: http://eureka7002.com:7002/eureka #单机版，指向自己




