server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
      base-url: http://localhost:9411 #zipkin监控界面地址
      sleuth:
        sampler:
          #采样率值介于0到1之间,0不采,0.5采一半,1则表示全部采集
         probability: 1
  datasource:
    #数据库驱动
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    #数据源名称
    name: defaultDataSource
    #数据库连接地址 本地 localhost 服务器 192.168.31.22
    url: jdbc:mysql://localhost:3306/cloud_alibaba?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=true&amp;serverTimezone=Asia/Shanghai
    #数据库用户名&密码    本地 root 服务器 chen
    username: root
    password: 123456


mybatis:
  #配置mybatis扫描路径
  mapper-locations: classpath:mapper/*.xml
  #指定Mybatis的实体类目录
  type-aliases-package: com.cl.springcloud.pojo


eureka:
  client:
    #表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓,集群必须设置true才能配合ribbon使用负载均衡
    fetchRegistry: true
    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      #defaultZone: http://localhost:7001/eureka  #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  #自定义服务名称（实例id）
  instance:
    instance-id: payment8001
    #访问路径可以显示ip地址
    prefer-ip-address: true
#    #----------关闭自我保护后的配置,正式环境不建议使用，一般用于生产环境排除----------
#    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
#    lease-renewal-interval-in-seconds: 1
#    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除服务
#    lease-expiration-duration-in-seconds: 2







