server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由  原来只可以这样访问：http://localhost:9527/payment/lb  配置之后还可以这样：http://localhost:9527/CLOUD-PAYMENT-SERVICE/payment/lb
      routes:
        #路由的ID,没有固定规则但要求唯一,建议配合服务名
        - id: payment_routh
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          #lb://serviceName是spring cloud gateway在微服务中自动为我们创建的负载均衡uri  (使用微服务实现动态路由)
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            #断言,路径相匹配的进行路由  配置之前地址：http://localhost:8001/payment/getPaymentById  配置之后：http://localhost:9527/payment/getPaymentById
            - Path=/payment/getPaymentById/**

        - id: payment_routh2
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          #lb://serviceName是spring cloud gateway在微服务中自动为我们创建的负载均衡uri  (使用微服务实现动态路由)
          uri: lb://CLOUD-PAYMENT-SERVICE
          #Predicate有不同的Http请求匹配，Path、After、Before...
          predicates:
            #断言,路径相匹配的进行路由
            - Path=/payment/lb/**
            #这个时间点之后才能访问
            - After=2022-06-22T13:58:59.866+08:00[Asia/Shanghai]
            #带有cookie的信息才能访问 http://localhost:9527/payment/lb --cookie "username=zzyy"
            #- Cookie=username,zzyy

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka




